#!/usr/bin/env python3
"""Generate the pinned tool mirror. Pass a Sure checkout to refresh its manifest.
Without --upstream this checks generated Swift against the committed manifest offline.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / 'Docs/AssistantTools.json'
OUTPUT = ROOT / 'App/Infrastructure/Assistant/SureToolInventory.swift'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--upstream', type=Path)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
pin = re.search(r'Commit: `([0-9a-f]{40})`', (ROOT / 'Docs/SureContractBaseline.md').read_text()).group(1)
if args.upstream:
    upstream = args.upstream
    revision = subprocess.check_output(['git', '-C', str(upstream), 'rev-parse', 'HEAD'], text=True).strip()
    if revision != pin:
        raise SystemExit('Upstream checkout must match Docs/SureContractBaseline.md')
    registry = (upstream / 'app/models/assistant.rb').read_text()
    preview = re.search(r'PREVIEW_FUNCTION_CLASSES = \[(.*?)\]', registry, re.S).group(1)
    names = set(re.findall(r'Function::(\w+)', registry))
    entries = []
    for path in sorted((upstream / 'app/models/assistant/function').glob('*.rb')):
        source = path.read_text()
        match = re.search(r'class Assistant::Function::(\w+) < Assistant::Function', source)
        if not match:
            continue  # Ruby mixins are not callable tools.
        cls = match.group(1)
        if cls not in names:
            raise SystemExit(f'Unregistered function needs review: {cls}')
        name = re.search(r'def name\s+"([a-z_]+)"', source).group(1)
        entries.append(dict(name=name, rubyClass=cls, preview=f'Function::{cls}' in preview,
                            sourceSHA256=hashlib.sha256(path.read_bytes()).hexdigest()))
    if {e['rubyClass'] for e in entries} != names:
        raise SystemExit('Registry contains an unmirrored function')
    manifest = dict(revision=pin, tools=entries)
    manifest_text = json.dumps(manifest, indent=2) + '\n'
    if args.check:
        if MANIFEST.read_text() != manifest_text:
            raise SystemExit('Upstream tool source drift: regenerate and review the manifest')
    else:
        MANIFEST.write_text(manifest_text)
else:
    manifest = json.loads(MANIFEST.read_text())
if manifest['revision'] != pin:
    raise SystemExit('Tool inventory revision differs from contract baseline')
entries = manifest['tools']
if len({e['name'] for e in entries}) != len(entries):
    raise SystemExit('Duplicate tool names')
def swift_case(name):
    first, *rest = name.split('_')
    return first + ''.join(s.title() for s in rest)
lines = ['// Generated by .github/scripts/sync_assistant_tools.py. Do not edit.',
         '// Availability and read-only policy live in SureToolPolicy.swift.',
         'enum SureToolInventory: String, CaseIterable, Sendable {']
lines += [f'  case {swift_case(e["name"])} = "{e["name"]}"' for e in entries]
lines += ['', f'  static let upstreamRevision = "{pin}"', '', '  var requiresPreview: Bool {', '    switch self {']
lines += [f'    case {", ".join("." + swift_case(e["name"]) for e in entries if e["preview"])}: true',
          '    default: false', '    }', '  }', '}', '']
output = '\n'.join(lines)
if args.check:
    if OUTPUT.read_text() != output:
        raise SystemExit('Tool mirror drift: run python3 .github/scripts/sync_assistant_tools.py')
else:
    OUTPUT.write_text(output)
