// Generated by .github/scripts/sync_assistant_tools.py. Do not edit.
// Availability and read-only policy live in SureToolPolicy.swift.
enum SureToolInventory: String, CaseIterable, Sendable {
  case createCategory = "create_category"
  case createGoal = "create_goal"
  case createTag = "create_tag"
  case getAccountStatement = "get_account_statement"
  case getAccounts = "get_accounts"
  case getBalanceSheet = "get_balance_sheet"
  case getBudget = "get_budget"
  case getCategories = "get_categories"
  case getHoldings = "get_holdings"
  case getIncomeStatement = "get_income_statement"
  case getInsights = "get_insights"
  case getMerchants = "get_merchants"
  case getRecurringTransactions = "get_recurring_transactions"
  case getStatementCoverage = "get_statement_coverage"
  case getTags = "get_tags"
  case getTransactions = "get_transactions"
  case getValuations = "get_valuations"
  case importBankStatement = "import_bank_statement"
  case listAccountStatements = "list_account_statements"
  case recordValuation = "record_valuation"
  case searchFamilyFiles = "search_family_files"
  case updateBudget = "update_budget"
  case updateCategory = "update_category"
  case updateTag = "update_tag"
  case updateTransaction = "update_transaction"
  case uploadAccountStatement = "upload_account_statement"

  static let upstreamRevision = "5594f8bc94c8e659838cac70d826bbcaeaa3bae2"

  var requiresPreview: Bool {
    switch self {
    case .getAccountStatement, .getInsights, .getStatementCoverage, .getValuations, .listAccountStatements, .recordValuation, .uploadAccountStatement: true
    default: false
    }
  }
}
